definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: -49
    expanded: false
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
_core:
  default_config_hash: pmBg0Q6hjZZ_Ln5w6Io2IwI8UyjxZUEytr3HFfba6_g
