hotlink: false
origin: 'http://dev-newupstream.pantheonsite.io'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
_core:
  default_config_hash: cdU-7ks7Jie2cQ6Sly5BTNM-kr-gPm3KWODjkXdt8m8
