name: 'Seussbook Press'
mail: tim@electriccitizen.com
slogan: 'The bird'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: 2aDl0dDrCQO2R73NHK51xpKXZ9w39d7y46AhHKlQEjU
uuid: 1f64525a-fd8e-40cd-80c1-c441c5592c5f
