check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - tim@electriccitizen.com
  threshold: all
_core:
  default_config_hash: p_7gVY8QZqeb-pi0jLX38mHwNn6KxHToLofBhao2RHE
